name: Testing local output

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gradio huggingface_hub torch transformers accelerate
    - name: Run tests
      run: |
        run: |
        python -c """
          from app import respond, base_message
          import time

          def test_local():
              # Set up input parameters
              message = 'What is the meaning of life'
              history = []
              system_message_val = base_message
              temperature = 0.7
              practicality = 0.8  # This should modify the system message to provide actionable advice
              max_new_tokens = 256
              use_local_model = True

              start_time = time.time()

              # Call the respond function
              result = list(respond(
                  message=message,
                  history=history,
                  system_message_val=system_message_val,
                  temperature=temperature,
                  practicality=practicality,
                  max_new_tokens=max_new_tokens,
                  use_local_model=use_local_model
              ))

              end_time = time.time()
              runtime = end_time - start_time

              final_history, final_system_message = result[-1]
              print('Runtime: ', runtime)
              print('Final conversation history:', final_history)
              print('Final system message:', final_system_message)

          if __name__ == '__main__':
              test_local()
                  """
